### ISSUE TITLE
CEUR-WS scraper fails on empty pages

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#2317]
**Describe the bug**
CEUR-WS scraper fails on empty pages 

**To Reproduce**
1. `python -m scholia.scrape.ceurws proceedings-url-to-quickstatements https://ceur-ws.org/Vol-3443/`
2. `AttributeError: 'NoneType' object has no attribute 'split'`

```
Traceback (most recent call last):
  File ".../python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File ".../python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File ".../scholia/scholia/scrape/ceurws.py", line 406, in <module>
    main()
  File "../scholia/scholia/scrape/ceurws.py", line 398, in main
    qs = proceedings_url_to_quickstatements(url, iso639=iso639)
  File ".../scholia/scholia/scrape/ceurws.py", line 198, in proceedings_url_to_quickstatements
    papers = tree_to_papers(tree, proceedings, proceedings_q=q,
  File ".../scholia/scholia/scrape/ceurws.py", line 157, in tree_to_papers
    number_of_pages = pages_to_number_of_pages(pages)
  File ".../scholia/scholia/utils.py", line 135, in pages_to_number_of_pages
    page_elements = pages.split('-')
AttributeError: 'NoneType' object has no attribute 'split'
```

**Expected behavior**
Quickstatements should be generated

**Additional context**

**Comment by fnielsen** [comment]
The `CEURPAGES` element is empty: `<span class="CEURPAGES"></span>`
