### ISSUE TITLE
Problem with wb_get_topic_latest_works

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#2531]
Problem with the topic aspect and perhaps author aspect. 

```
ERROR in app: Exception on /topic/Q189849/latest-works/rss [GET]
Traceback (most recent call last):
  File "/data/project/scholia/www/python/venv/lib/python3.9/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/data/project/scholia/www/python/venv/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/data/project/scholia/www/python/venv/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/data/project/scholia/www/python/venv/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/project/scholia/www/python/venv/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/project/scholia/www/python/venv/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/project/scholia/www/python/venv/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/project/scholia/www/python/venv/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "./scholia/app/views.py", line 2017, in show_topic_rss
    response_body = wb_get_topic_latest_works(q)
  File "./scholia/rss.py", line 410, in wb_get_topic_latest_works
    data = response.json()
  File "/data/project/scholia/www/python/venv/lib/python3.9/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by egonw** [comment]
It seems to time out for me. If it does, I can imagine the returned content is not JSON, causing the `simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` ?

**Comment by egonw** [comment]
Actually, not sure... this is the SPARQL it is running and that works fine: https://w.wiki/BWbk

**Comment by egonw** [comment]
Actually, works in the browser too. @fnielsen, how can I reproduce the error?
